sudo: required
services:
  - docker

before_install:
  - docker build -t mugeesh/react-fibonacci -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mugeesh/react-fibonacci npm run test -- --watchAll=false
  #- docker run mugeesh/frontend_react_pro npm test -- ---coverage

after_success:
  - docker build -t mugeesh/multi-client ./client
  - docker build -t mugeesh/multi-nginx ./nginx
  - docker build -t mugeesh/multi-server ./server
  - docker build -t mugeesh/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mugeesh/multi-client
  - docker push mugeesh/multi-nginx 
  - docker push mugeesh/multi-server  
  - docker push mugeesh/multi-worker  

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-284249289744
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY



